### ISSUE TITLE
Core segfaults when closed

### ISSUE THREAD

**Issue by vanfanel** [libretro/Dinothawr#12]
Hi there,

This core segfaults badly when closed. It can be either by closing the core, or trying to load another core from the RA menu.

**Comment by Tatsuya79** [comment]
Problem probably lies within RA.

1.7.5 826c77d523 2018-10-02 GOOD
1.7.6 9750719074 2019-02-03 BAD

suspect:
2019-01-08 big Vorbis PR https://github.com/libretro/RetroArch/pull/7938

**Comment by SimpleTease** [comment]
I think this would work but haven't tested.

```
void retro_unload_game(void)
{
   // Workaround a crash on Windows & Android because the callbacks are invoked after the DLL/SO was unloaded
   struct retro_audio_callback cb = { nullptr, nullptr };
   use_audio_cb = environ_cb(RETRO_ENVIRONMENT_SET_AUDIO_CALLBACK, &cb);

   game.reset();
}
```

**Comment by twinaphex** [comment]
@SimpleTease Would be worthwhile if you could find a fix on the RetroArch side. There are not that many cores yet implementing the audio callback so its possible this was overlooked.

**Comment by Tatsuya79** [comment]
On win x64 with xaudio there's no audio at all and bringing the menu up with F1 corrupts everything and crash.
with dsound it's just an exit crash.

It was fine around RA 1.7.5.

**Comment by SimpleTease** [comment]
DSound doesn't give me any problems. XAudio has no sound and generates heavy RA corruption (missing assets, depth problems, no playlist updates, bad hotkeys, exit crash). I haven't traced back to 1.7.5 but it'll be interesting to bisect the problem commit(s).

I did test the core without any callbacks and XAudio behaved okay. Having a non-multithreaded core option might be handy as a fallback. Still I'll see where my adventures take me.

**Comment by SimpleTease** [comment]
I've identified a list of problems.

Core:
- Shouldn't generate samples when empty. Sometimes audio callback gets polled 2x before the music code is run again.

Frontend:
- XAudio has no audio callback support. No music.
- On unload game, frontend should shutdown audio, timer callbacks. Crash on exit.
- ?? Frontend is misbehaving when no audio is coming in.
- ?? Frontend should not send audio, timer callbacks when `Pause Content When Menu is Active` is `ON`.

**Comment by twinaphex** [comment]
OK, with this PR merged now, what's the current status of this issue?

**Comment by Tatsuya79** [comment]
Should be fixed.

#11830 #11831
